services:
  - type: web
    name: farmaservicios-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"
    envVars:
      - key: DATABASE_URL
        sync: false
